### ISSUE TITLE
estrutura de contours e set points

### ISSUE THREAD

**Issue by ademirtc** [dulpneto/MAC5749#1]
Olá pessoal, uma duvida, têm definido alguma estrutura para os contours, só é uma matriz ou um diccionario?
Para desenhar desde um contour o grupo 1 precisa conhecer as dimensões da imagem original, seria bom ter esses dados.

Também, o resultado da função **extract_contours**  retorna a seguinte matriz, 
```
A = np.array([[0,0,0,0],[0,1,1,0],[0,0,0,0]])
#[[0 0 0 0]
#[0 1 1 0]
# [0 0 0 0]]
contour = extract_contours(A)
print(contour[0])
[[ 2.  2.]
 [ 2.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 1.  3.]
 [ 2.  2.]]
```
mas acho que deveria retornar
`
 [[0,1,0]
 [1,2,1]
 [2,2,2]
 [3,1,3]
 [4,0,2]
 [5,0,1]]
`
a primeira coluna é o parametro t que pode ser não necessario se é o indice da matriz.

**Comment by ademirtc** [comment]
Olá pessoal, a função extract_contours retorna uma lista de listas e não uma matriz de nx3 

```
>> aContour = extract_contours(dataset['bitmaps'][123])
print(type(aContour))
<class 'list'>
print(type(aContour[0]))
<class 'list'>
```

**Comment by dulpneto** [comment]
Ola,
Alterei o retorno. 
>> contours = extract_contours(img_example)
print(type(contours))
<class 'numpy.ndarray'>
print(type(contours[0]))
<class 'numpy.ndarray'>
print(type(contours[0][0]))
<class 'numpy.ndarray'>

**Comment by ademirtc** [comment]
Olá, com a linha ``` print(aContour[10][1]) ``` a gente espera o valor de x no t = 10,
mas retorna o array [t x y]

```
>>> aContour = extract_contours(dataset['bitmaps'][100])    
>>> print(aContour[10][1])
[ 10 84 52]
```

Outra duvida, por exemplo com a imagem da letra **i**, qual contorno é retornado, uma opção (depende da implementação de vocês) pode ser ter um parametro para retornar o de maior perimetro ou um array com todos os contornos.

**Comment by dulpneto** [comment]
O retorno é uma lista de contornos, sendo que é ordenado do maior para o menor.
Então para obter o maior contorno: aContour[0]
Para obter o valor de x para o t = 10: aContour[0][10][1]
