### ISSUE TITLE
Completar página de tipos de dados

### ISSUE THREAD

**Issue by mateusriva** [dulpneto/MAC5749#2]
Olá! Por favor, um de cada grupo, pode completar a página [wiki/data-types](https://github.com/dulpneto/MAC5749/wiki/data-types) com as informações do seu tipo de dados? Assim, quando o grupo do website começar, fica mais fácil pra eles.

- [ ]  Parametric Contour (type: type_contour): [group3 add details]
- [x]  Point Set (type: type_point_set): [group1 add details]
- [ ]  Landmarks (type: type_landmarks): [add details]
- [ ]  Complex Contour (type: type_complex_contour): [add details]
- [ ]  Polar Complex Contour (type: type_polar_contour): [add details]

**Comment by ademirtc** [comment]
Para padronizar a documentação do codigo, seria bom considerar o seguinte link https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

De ahi, é facil gerar uma pagina online com a documentação
https://dulpneto.github.io/MAC5749/

um teste com imagens 
https://dulpneto.github.io/MAC5749/sarpy.binaryScale.html

**Comment by mateusriva** [comment]
Não é mais relevante.
