### ISSUE TITLE
Atualizar para Shape

### ISSUE THREAD

**Issue by mateusriva** [dulpneto/MAC5749#3]
O formato "Shape" está implementado em [sarpy/utils/shape.py](../blob/bac58ce/sarpy/utils/shape.py). Eu sobrecarreguei os operadores de brackets (`a[x] = y`, `y = a[x]`), `len`, `all` e `any` - estamos assumindo que todos os tipos de dados serão, fundamentalmente, arrays NumPy.

Por favor, revisem seus exemplos e verifiquem se está tudo funcionando. Na pior das hipóteses, vocês sempre podem acessar a *raw data* usando `shape.data`.

**Comment by dulpneto** [comment]
Revisei o exemplo do grupo 3 e está tudo OK!

**Comment by mateusriva** [comment]
Não é mais relevante.
