### ISSUE TITLE
Atualizar para arquivos únicos (conversões e transformações)

### ISSUE THREAD

**Issue by mateusriva** [dulpneto/MAC5749#4]
Criamos um esqueleto de arquivo para unificar as conversões e transformações (e permitir acesso vindo de fontes externas à biblioteca):
* [sarpy/conversions.py](../blob/master/sarpy/conversions.py)
* [sarpy/transformations.py](../blob/master/sarpy/transformations.py)
Também é bom consultar o * [sarpy/__init__.py](../blob/master/sarpy/__init__.py) para saber quais são as funções que estão expostas ao usuário. (nós tentamos deixar o mais simples possível ao usuário médio; ele não precisa saber de primeira que existem 36 funções de conversão)

Por favor, movam/comecem suas operações de transformação e conversão entre tipos nestes arquivos. Nós movemos algumas das funções que estavam soltas para dentro desses arquivos, mas seria bom os autores originais darem uma passada de olho (e fazer uns testes, e correr uns exemplos) nelas.

**Comment by dulpneto** [comment]
Corrigi a função shape_shift que foi movida para o arquivo sarpy/transformations.py, alterei o exemplo para utilizar a nova função e apaguei o arquivo antigo (sarpy/binaryShift.py)

**Comment by mateusriva** [comment]
Deprecado.
